-- /supabase/migrations/add-bundle-listing-column.sql
-- Adds bundle_listing JSONB column to funnels table
-- This fixes the "column funnels.bundle_listing does not exist" error
-- The code saves bundle data to this column, not to a separate bundles table

ALTER TABLE funnels ADD COLUMN IF NOT EXISTS bundle_listing JSONB;

COMMENT ON COLUMN funnels.bundle_listing IS 'Bundle listing data (title, description, tags, pricing) - generated by Task 14';
